In [ ]:
# File name:  data-import-citibike.ipynb

In [ ]:
# ------------------------
# Rob Gauer
# Citi-Bike
# 20-Tableau Homework
# Date August 1, 2020
# ------------------------
#
# Data sets import, review, and concatenate into one file. 
# Write to one csv file located to folder called:  data_output/citi-bike-concatenated-dataset.csv
# Data selection chosen for excercise is:  January 2019 to June 2020. i.e. Year 2019 and January to June of 2020.
#

In [1]:
# Setup and Dependancies
import pandas as pd
import glob
import matplotlib.pyplot as plt
import scipy.stats as st
import numpy as np
import os

In [2]:
# Read data all file names and append datasets into one dataframe
path =r'C:\Users\Rober\Desktop\GAUER_Data_Visualization\github_gauer_homework\20_Tableau\datasets'
all_files = glob.glob(os.path.join(path, "*.csv"))

df_from_each_file=(pd.read_csv(f) for f in all_files)
concatenated_df = pd.concat(df_from_each_file, ignore_index=True)

In [31]:
# Display the column names.
concatenated_df.columns

Index(['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender'],
      dtype='object')

In [28]:
# Display the dataset dataframe of data selection chosen for excercise of all year 2019 and year 2020 January to June.
concatenated_df

tripduration                 starttime                  stoptime  \
0                201  2019-01-01 03:09:09.7110  2019-01-01 03:12:30.8790   
1                505  2019-01-01 05:18:00.1060  2019-01-01 05:26:25.9050   
2                756  2019-01-01 10:36:33.3400  2019-01-01 10:49:10.2600   
3               1575  2019-01-01 12:43:38.6430  2019-01-01 13:09:54.5280   
4               1566  2019-01-01 12:43:39.6010  2019-01-01 13:09:46.5100   
...              ...                       ...                       ...   
542909          2828  2020-06-30 23:53:19.7380  2020-07-01 00:40:28.5760   
542910          2729  2020-06-30 23:54:44.0100  2020-07-01 00:40:13.6470   
542911          2788  2020-06-30 23:54:52.1920  2020-07-01 00:41:20.6500   
542912          2702  2020-06-30 23:56:14.6650  2020-07-01 00:41:16.7820   
542913          2649  2020-06-30 23:57:46.1490  2020-07-01 00:41:55.5060   

        start station id start station name  start station latitude  \
0                   3183     Exchange Place               40.716247   
1                   3183     Exchange Place               40.716247   
2                   3183     Exchange Place               40.716247   
3                   3183     Exchange Place               40.716247   
4                   3183     Exchange Place               40.716247   
...                  ...                ...                     ...   
542909              3199       Newport Pkwy               40.728745   
542910              3199       Newport Pkwy               40.728745   
542911              3199       Newport Pkwy               40.728745   
542912              3199       Newport Pkwy               40.728745   
542913              3199       Newport Pkwy               40.728745   

        start station longitude  end station id    end station name  \
0                    -74.033459            3214    Essex Light Rail   
1                    -74.033459            3638       Washington St   
2                    -74.033459            3192  Liberty Light Rail   
3                    -74.033459            3638       Washington St   
4                    -74.033459            3638       Washington St   
...                         ...             ...                 ...   
542909               -74.032108            3199        Newport Pkwy   
542910               -74.032108            3199        Newport Pkwy   
542911               -74.032108            3199        Newport Pkwy   
542912               -74.032108            3199        Newport Pkwy   
542913               -74.032108            3199        Newport Pkwy   

        end station latitude  end station longitude  bikeid    usertype  \
0                  40.712774             -74.036486   29612  Subscriber   
1                  40.724294             -74.035483   29213  Subscriber   
2                  40.711242             -74.055701   26164  Subscriber   
3                  40.724294             -74.035483   29672    Customer   
4                  40.724294             -74.035483   29522    Customer   
...                      ...                    ...     ...         ...   
542909             40.728745             -74.032108   18351    Customer   
542910             40.728745             -74.032108   44401    Customer   
542911             40.728745             -74.032108   42334    Customer   
542912             40.728745             -74.032108   42463    Customer   
542913             40.728745             -74.032108   42468    Customer   

        birth year  gender  
0             1993       1  
1             1972       2  
2             1985       1  
3             1969       0  
4             1969       0  
...            ...     ...  
542909        1969       0  
542910        1969       0  
542911        1969       0  
542912        1969       0  
542913        1998       2  

[542914 rows x 15 columns]

In [29]:
# Review the dataset for clean up needs or record differences to investigate and correct.
concatenated_df.count()

tripduration               542914
starttime                  542914
stoptime                   542914
start station id           542914
start station name         542914
start station latitude     542914
start station longitude    542914
end station id             542914
end station name           542914
end station latitude       542914
end station longitude      542914
bikeid                     542914
usertype                   542914
birth year                 542914
gender                     542914
dtype: int64

In [30]:
# Statistically describe the dataset.
concatenated_df.describe()

tripduration  start station id  start station latitude  \
count  5.429140e+05     542914.000000           542914.000000   
mean   9.405912e+02       3297.362590               40.722609   
std    1.144516e+04        175.268228                0.007118   
min    6.100000e+01       3183.000000               40.709651   
25%    2.430000e+02       3195.000000               40.718211   
50%    3.760000e+02       3210.000000               40.721525   
75%    6.970000e+02       3276.000000               40.727224   
max    2.566420e+06       3792.000000               40.748716   

       start station longitude  end station id  end station latitude  \
count            542914.000000   542914.000000         542914.000000   
mean                -74.046462     3295.857051             40.722251   
std                   0.011112      183.456098              0.007001   
min                 -74.083639       83.000000             40.674181   
25%                 -74.050656     3192.000000             40.717733   
50%                 -74.043845     3209.000000             40.721124   
75%                 -74.038051     3276.000000             40.727224   
max                 -74.032108     3992.000000             40.842842   

       end station longitude         bikeid     birth year         gender  
count          542914.000000  542914.000000  542914.000000  542914.000000  
mean              -74.045972   31189.421104    1981.269173       1.151210  
std                 0.011078    5750.439740      10.428549       0.541882  
min               -74.083639   14531.000000    1887.000000       0.000000  
25%               -74.050389   26431.000000    1974.000000       1.000000  
50%               -74.043117   29474.000000    1984.000000       1.000000  
75%               -74.038051   29654.000000    1989.000000       1.000000  
max               -73.932077   44543.000000    2004.000000       2.000000

In [6]:
# Display data types.
concatenated_df.dtypes

tripduration                 int64
starttime                   object
stoptime                    object
start station id             int64
start station name          object
start station latitude     float64
start station longitude    float64
end station id               int64
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                       int64
usertype                    object
birth year                   int64
gender                       int64
dtype: object

In [7]:
# Number of bike trips count total usage. 524914 trips (ridership usage).
bikeids_trips_count = concatenated_df["bikeid"].count()
bikeids_trips_count

542914

In [8]:
# Bike uiquie ids.
bikeids_unique_count = concatenated_df["bikeid"].unique()
bikeids_unique_count

array([29612, 29213, 26164, ..., 44492, 43489, 37829], dtype=int64)

In [26]:
# Start station ids.
start_station_ids_unique = concatenated_df["start station id"].unique()
start_station_ids_unique

array([3183, 3184, 3185, 3186, 3187, 3191, 3192, 3193, 3194, 3195, 3196,
       3198, 3199, 3201, 3202, 3203, 3205, 3206, 3207, 3209, 3210, 3211,
       3212, 3213, 3214, 3220, 3225, 3267, 3268, 3269, 3270, 3272, 3273,
       3275, 3276, 3277, 3278, 3279, 3280, 3281, 3426, 3481, 3483, 3638,
       3639, 3640, 3677, 3678, 3679, 3681, 3694, 3791, 3792], dtype=int64)

In [19]:
# Start station names.
start_station_names_unique = concatenated_df["start station name"].unique()
start_station_names_unique

array(['Exchange Place', 'Paulus Hook', 'City Hall', 'Grove St PATH',
       'Warren St', 'Union St', 'Liberty Light Rail', 'Lincoln Park',
       'McGinley Square', 'Sip Ave', 'Riverview Park', 'Heights Elevator',
       'Newport Pkwy', 'Dey St', 'Newport PATH', 'Hamilton Park',
       'JC Medical Center', 'Hilltop', 'Oakland Ave', 'Brunswick St',
       'Pershing Field', 'Newark Ave', 'Christ Hospital',
       'Van Vorst Park', 'Essex Light Rail', '5 Corners Library',
       'Baldwin at Montgomery', 'Morris Canal', 'Lafayette Park',
       'Brunswick & 6th', 'Jersey & 6th St', 'Jersey & 3rd',
       'Manila & 1st', 'Columbus Drive', 'Marin Light Rail',
       'Communipaw & Berry Lane', 'Monmouth and 6th', 'Dixon Mills',
       'Astor Place', 'Leonard Gordon Park', 'JCBS Depot', 'York St',
       'Montgomery St', 'Washington St', 'Harborside', 'Journal Square',
       'Glenwood Ave', 'Fairmount Ave', 'Bergen Ave', 'Grand St',
       'Jackson Square', 'Hoboken Ave at Monmouth St',
    

In [20]:
# Least used start station.
start_station_names_min = concatenated_df["start station name"].min()
start_station_names_min

'5 Corners Library'

In [21]:
# Most used start station.
start_station_names_max = concatenated_df["start station name"].max()
start_station_names_max

'York St'

In [27]:
# End station ids.
end_station_ids_unique = concatenated_df["end station id"].unique()
end_station_ids_unique

array([3214, 3638, 3192, 3205, 3277, 3196, 3202, 3267, 3183, 3681, 3270,
       3184, 3185, 3639, 3186, 3207, 3272, 3187, 3273, 3481, 3199, 3276,
       3203, 3213, 3269, 3225, 3275, 3278, 3209, 3483, 3212, 3193, 3279,
       3211, 3194, 3210, 3195, 3268, 3677, 3679, 3280, 3640, 3694, 3198,
       3201, 3206, 3678, 3191, 3220, 3281, 3426, 3709,  514,  523,  513,
        459,  327,  224, 3472, 3002,  477,  468, 3170, 3258,  526,  358,
       3541,  303,  311, 3168, 3750,  487,  195, 3791,  315,  383,  426,
        504,  447,  524, 3360, 3686,  337, 3167, 3664,  217, 3547, 3461,
       3792,  505,  484,  279,  304,  285,  456, 3435,  464,  347, 3540,
        116,  127, 3674, 3467,  363,  496,  309,  319,  392,  351,  128,
        376,  525,  355,  254,  268,  442,  146,  377,  519, 2008, 3256,
         83, 3649,  244, 3992, 3623,  476,  480, 3578, 3443,  308, 3629,
        489,  534,  143,  173,  518], dtype=int64)

In [23]:
# End station names.
end_station_names_unique = concatenated_df["end station name"].unique()
end_station_names_unique

array(['Essex Light Rail', 'Washington St', 'Liberty Light Rail',
       'JC Medical Center', 'Communipaw & Berry Lane', 'Riverview Park',
       'Newport PATH', 'Morris Canal', 'Exchange Place', 'Grand St',
       'Jersey & 6th St', 'Paulus Hook', 'City Hall', 'Harborside',
       'Grove St PATH', 'Oakland Ave', 'Jersey & 3rd', 'Warren St',
       'Manila & 1st', 'York St', 'Newport Pkwy', 'Marin Light Rail',
       'Hamilton Park', 'Van Vorst Park', 'Brunswick & 6th',
       'Baldwin at Montgomery', 'Columbus Drive', 'Monmouth and 6th',
       'Brunswick St', 'Montgomery St', 'Christ Hospital', 'Lincoln Park',
       'Dixon Mills', 'Newark Ave', 'McGinley Square', 'Pershing Field',
       'Sip Ave', 'Lafayette Park', 'Glenwood Ave', 'Bergen Ave',
       'Astor Place', 'Journal Square', 'Jackson Square',
       'Heights Elevator', 'Dey St', 'Hilltop', 'Fairmount Ave',
       'Union St', '5 Corners Library', 'Leonard Gordon Park',
       'JCBS Depot', 'W 15 St & 6 Ave', '12 Ave & W 40 

In [24]:
# Least used destination station.
end_station_names_min = concatenated_df["end station name"].min()
end_station_names_min

'1 Ave & E 16 St'

In [25]:
# Most used destination station.
end_station_names_max = concatenated_df["end station name"].max()
end_station_names_max

'York St'

In [22]:
# Usertypes found within the dataset.
usertype_unique = concatenated_df["usertype"].unique()
usertype_unique

array(['Subscriber', 'Customer'], dtype=object)

In [14]:
# Genders found within the dataset.
gender_unique = concatenated_df["gender"].unique()
gender_unique

array([1, 2, 0], dtype=int64)

In [15]:
# Dislay all of the riders birth years found within the dataset. 
# Note within dataset contains the year of 1887, 1888, 1889...
birth_year_unique = concatenated_df["birth year"].unique()
birth_year_unique

array([1993, 1972, 1985, 1969, 1986, 1992, 1994, 1990, 1996, 1987, 1960,
       1977, 1966, 1975, 1982, 1984, 1981, 1988, 1971, 1958, 1968, 1976,
       1980, 1965, 1979, 1991, 1983, 1989, 1962, 1954, 1974, 1963, 1970,
       1978, 1955, 1967, 1941, 1961, 1973, 1997, 1949, 1995, 1957, 1998,
       1952, 1953, 1956, 1959, 1888, 1964, 1951, 1999, 2000, 1950, 1944,
       2001, 2002, 1947, 1904, 2003, 1918, 1940, 1946, 1889, 1900, 1948,
       1887, 1905, 1901, 1945, 1938, 1939, 2004, 1920], dtype=int64)

In [16]:
# Dataset average (mean) rider birth year is 1981.
birth_year_mean = concatenated_df["birth year"].mean()
birth_year_mean

1981.2691733865768

In [17]:
# Dataset minimum rider birth year is 1887. 
# This is an error in their system. Is this one record? 
# Or does it call out that birth year data may not be truthful. 
birth_year_min = concatenated_df["birth year"].min()
birth_year_min

1887

In [18]:
# Dataset maximum rider birth year is 2004.
birth_year_max = concatenated_df["birth year"].max()
birth_year_max

2004

In [39]:
#output_file_path=os.path.join("..","data_output", "citi-bike-concatenated-dataset.csv")
concatenated_df.to_csv('data-output/citi-bike-concatenated-dataset.csv', encoding='utf-8')

In [ ]:
# EOF #